version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    volumes:
      - .:/app
    environment:
      - TOKEN=7489778031:AAFW7ZxD4H3wQcQ4rMmSOOFFzY_-4vRCeMg
    restart: always
